CREATE DATABASE IF NOT EXISTS crud_php;
USE crud_php;

CREATE TABLE usuarios (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nome VARCHAR(100),
  email VARCHAR(100) UNIQUE,
  senha VARCHAR(255)
);

CREATE TABLE produtos (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nome VARCHAR(100) NOT NULL,
  preco DECIMAL(10,2) NOT NULL,
  quantidade INT NOT NULL,
  descricao TEXT,
  imagem VARCHAR(255),
  data_criacao DATETIME DEFAULT CURRENT_TIMESTAMP
); 